#!/usr/bin/env node
/**
 * Creates the schema in Neon.
 *
 *   npm run db:migrate
 *
 * The app also creates the schema lazily on first use, so this is mainly for
 * running it once up front — before the first deploy, or after changing the
 * connection string — and for confirming the database is reachable at all.
 */

import { readFileSync, existsSync } from 'node:fs';
import { neon } from '@neondatabase/serverless';

for (const file of ['.env.local', '.env']) {
  if (!existsSync(file)) continue;
  for (const line of readFileSync(file, 'utf8').split(/\r?\n/)) {
    const m = /^\s*([A-Z0-9_]+)\s*=\s*(.*)$/.exec(line);
    if (m && process.env[m[1]] === undefined) {
      process.env[m[1]] = m[2].trim().replace(/^["']|["']$/g, '');
    }
  }
}

const url = process.env.DATABASE_URL || process.env.POSTGRES_URL || process.env.NEON_DATABASE_URL;
if (!url) {
  console.error('\n  x DATABASE_URL is not set. Paste your Neon connection string into .env.local.\n');
  process.exit(1);
}

const sql = neon(url);

const STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS users (
     id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     email          text NOT NULL UNIQUE,
     name           text NOT NULL,
     password_hash  text NOT NULL,
     role           text NOT NULL DEFAULT 'agent',
     active         integer NOT NULL DEFAULT 1,
     created_at     timestamptz NOT NULL DEFAULT now(),
     last_login_at  timestamptz
   )`,
  `CREATE TABLE IF NOT EXISTS leads (
     id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     jid               text NOT NULL UNIQUE,
     phone             text NOT NULL,
     push_name         text,
     name              text,
     city              text,
     profession        text,
     profile           text,
     goal              text,
     program           text,
     contact_time      text,
     language          text NOT NULL DEFAULT 'en',
     stage             text NOT NULL DEFAULT 'new',
     owner_user_id     integer REFERENCES users(id) ON DELETE SET NULL,
     priority          integer NOT NULL DEFAULT 0,
     board_order       double precision NOT NULL DEFAULT 0,
     bot_paused        integer NOT NULL DEFAULT 0,
     greeted           integer NOT NULL DEFAULT 0,
     stop_replying     integer NOT NULL DEFAULT 0,
     unread            integer NOT NULL DEFAULT 0,
     msg_count         integer NOT NULL DEFAULT 0,
     first_seen_at     timestamptz NOT NULL DEFAULT now(),
     last_message_at   timestamptz,
     last_inbound_at   timestamptz,
     last_bot_reply_at timestamptz,
     followup_sent_at  timestamptz,
     close_reason      text,
     expecting         text
   )`,
  `CREATE INDEX IF NOT EXISTS idx_leads_stage ON leads(stage)`,
  `CREATE INDEX IF NOT EXISTS idx_leads_last_msg ON leads(last_message_at DESC)`,
  `CREATE TABLE IF NOT EXISTS messages (
     id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     lead_id         integer NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
     direction       text NOT NULL,
     author          text NOT NULL DEFAULT 'customer',
     kind            text NOT NULL DEFAULT 'text',
     body            text NOT NULL DEFAULT '',
     intent          text,
     trigger_no      integer,
     wa_message_id   text,
     status          text NOT NULL DEFAULT 'ok',
     error           text,
     sent_by_user_id integer REFERENCES users(id) ON DELETE SET NULL,
     created_at      timestamptz NOT NULL DEFAULT now()
   )`,
  `CREATE INDEX IF NOT EXISTS idx_messages_lead ON messages(lead_id, id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_messages_waid ON messages(wa_message_id)
     WHERE wa_message_id IS NOT NULL`,
  `CREATE TABLE IF NOT EXISTS escalations (
     id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     lead_id       integer NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
     trigger_no    integer NOT NULL,
     topic         text NOT NULL,
     inbound_text  text,
     resolved      integer NOT NULL DEFAULT 0,
     resolved_by   integer REFERENCES users(id) ON DELETE SET NULL,
     resolved_at   timestamptz,
     created_at    timestamptz NOT NULL DEFAULT now()
   )`,
  `CREATE INDEX IF NOT EXISTS idx_esc_lead ON escalations(lead_id)`,
  `CREATE INDEX IF NOT EXISTS idx_esc_open ON escalations(resolved, created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS notes (
     id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     lead_id     integer NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
     user_id     integer REFERENCES users(id) ON DELETE SET NULL,
     body        text NOT NULL,
     created_at  timestamptz NOT NULL DEFAULT now()
   )`,
  `CREATE INDEX IF NOT EXISTS idx_notes_lead ON notes(lead_id, id DESC)`,
  `CREATE TABLE IF NOT EXISTS activity (
     id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     lead_id     integer REFERENCES leads(id) ON DELETE CASCADE,
     user_id     integer REFERENCES users(id) ON DELETE SET NULL,
     action      text NOT NULL,
     detail      text,
     created_at  timestamptz NOT NULL DEFAULT now()
   )`,
  `CREATE INDEX IF NOT EXISTS idx_activity_lead ON activity(lead_id, id DESC)`,
  `CREATE TABLE IF NOT EXISTS settings (
     key    text PRIMARY KEY,
     value  text NOT NULL
   )`,
  `CREATE TABLE IF NOT EXISTS blocked_outbound (
     id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     lead_id     integer REFERENCES leads(id) ON DELETE CASCADE,
     draft       text NOT NULL,
     pattern     text NOT NULL,
     created_at  timestamptz NOT NULL DEFAULT now()
   )`,
  `ALTER TABLE leads ADD COLUMN IF NOT EXISTS expecting text`,
];

const host = (() => {
  try {
    return new URL(url).host;
  } catch {
    return '(unparsed)';
  }
})();

console.log(`\n  Neon : ${host}\n`);

try {
  const [{ version }] = await sql.query('SELECT version() AS version');
  console.log(`  + connected — ${String(version).split(',')[0]}`);
} catch (e) {
  console.error(`  x cannot connect: ${e.message}`);
  console.error('    Check DATABASE_URL (use the pooled string, keep ?sslmode=require).\n');
  process.exit(1);
}

let done = 0;
for (const statement of STATEMENTS) {
  try {
    await sql.query(statement);
    done++;
  } catch (e) {
    console.error(`\n  x failed: ${statement.slice(0, 70).replace(/\s+/g, ' ')}…`);
    console.error(`    ${e.message}\n`);
    process.exit(1);
  }
}
console.log(`  + schema applied (${done} statements)`);

const tables = await sql.query(
  `SELECT table_name, (SELECT COUNT(*) FROM information_schema.columns c
      WHERE c.table_name = t.table_name AND c.table_schema = 'public')::int AS cols
     FROM information_schema.tables t
    WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
    ORDER BY table_name`,
);
for (const t of tables) console.log(`    ${t.table_name.padEnd(18)} ${t.cols} columns`);

const [{ n }] = await sql.query('SELECT COUNT(*)::int AS n FROM users');
console.log(
  n > 0
    ? `\n  ${n} account(s) exist — sign in at /login\n`
    : '\n  No accounts yet — open the app and create the first admin.\n',
);
